sudo: required
dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libirrlicht-dev
      - libxxf86vm-dev
      - freeglut3-dev
      - gcc-7
      - g++-7
      - libeigen3-dev
  coverity_scan:
    project:
      name: "projectchrono/chrono"
      description: "Build submitted via Travis CI"
      notification_email: dev@aas.io
      build_command_prepend: "mkdir build && cd build && cmake $CMAKE_EXTRA_FLAGS .."
      build_command: "make -j 4"
      branch_pattern: coverity_scan
compiler:
  - gcc
env:
  matrix:
    - CMAKE_EXTRA_FLAGS="-DCMAKE_BUILD_TYPE=Release -DENABLE_MODULE_IRRLICHT=ON -DENABLE_MODULE_POSTPROCESS=ON -DBUILD_TESTING=ON -DBUILD_BENCHMARKING=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DENABLE_CXX11=ON"
    - CMAKE_EXTRA_FLAGS="-DCMAKE_BUILD_TYPE=Release -DENABLE_MODULE_VEHICLE=ON -DBUILD_TESTING=ON -DBUILD_BENCHMARKING=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DENABLE_CXX11=ON"
  global:
    - secure: "YY9gwr3+p3xwX7Kaw+j51JKjYdNl2oNBIHOBfXwLzVCh6F+HVIQAT7C9nSFH4O+brImwhDe7q3BzI1m0hdU5L1nyKtPjG5eolRafkvZYIVjvNduh65OS1rIzV9JibmEjqE6I9x1ndYaW3Yc8tdR6TVr+M2UK907jrBClUdv1uwE="
before_install:
  - |
    wget -q -O eigen.tar.gz https://bitbucket.org/eigen/eigen/get/3.3.4.tar.gz
    tar xzf eigen.tar.gz
    export CMAKE_INCLUDE_PATH="${CMAKE_INCLUDE_PATH:+$CMAKE_INCLUDE_PATH:}$PWD/eigen-eigen-5a0156e40feb"
before_script:
  - mkdir build && cd build
  - if [ "$CXX" = "g++" ]; then CXX=g++-7 CC=gcc-7 cmake $CMAKE_EXTRA_FLAGS ..; fi
script:
  - make -j 4
  - make test
branches:
  - except:
    - feature/mpi
notifications:
  recipients:
    - projectchrono-developers@googlegroups.com
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - chat.freenode.net#projectchrono
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
  slack:
    secure: BoCl/C15tcYX+55PQWPBEVCt/nw3j07qONSNecvuUEJ6UbyUKPbt+0HT0Vc2q6f7uphvvw8hRkTyk0XEGEcXAccmRJr9RsOCBvd3kQPdidooDBJ4dI1ZU9y2XcFUjB5VJuKzPgBYSfQSLbt1OVBNZ6ISw02UF1JNaC9DKtFRtSI=
